config/routes.rb
MacManager::Application.routes.draw do
  # devise_for :admins
  devise_for :admins, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}

  resources :manifests
  resources :devices
  # resources :devices do
    # match 'get_settings', via: :all #  => 'devices#get_settings'
  # end

  

  # You can have the root of your site routed with "root"
 root 'devices#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase
  get 'devices/:hardware_serial/get_settings' => 'devices#get_settings'
  get 'devices/:hardware_serial/get_resolution' => 'devices#get_resolution'
  
  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/device.rb
class Device < ActiveRecord::Base
  before_validation :correct_fields
  
  belongs_to :manifest

  scope :ordered, -> { includes(:manifest).order('manifests.name, room, number').references(:manifests) }
  
  # validates :hardware_serial, presence: true, uniqueness: true, length: { minimum: 12 }
  # validates :room, presence: true, format: { with: /\AR([0-9]{3})\z/ }
  # validates :number, uniqueness: true, numericality: { only_integer: true }, allow_blank: true
  # validates :resolution_x, numericality: { only_integer: true, greater_than_or_equal_to: 16, less_than_or_equal_to: 8192 }, allow_blank: true
  # validates :resolution_y, numericality: { only_integer: true, greater_than_or_equal_to: 16, less_than_or_equal_to: 8192 }, allow_blank: true
  # validates :mac_en, presence: true, uniqueness: true, format: { with: /\A([0-9A-F]{2}[:-]){5}([0-9A-F]{2})\z/ }
  # validates :mac_wifi, presence: true, uniqueness: true, format: { with: /\A([0-9A-F]{2}[:-]){5}([0-9A-F]{2})\z/ }
  # validates :ip, presence: true, format: { with: /\A10\.\d{1,3}\.\d{1,3}\.\d{1,3}\z/ }
  # validates :manifest, presence: true
  # validates :model, presence: true, inclusion: { within: %w(iMac MacMini) }
  
  def correct_fields
    self.mac_en.upcase! if self.mac_en.present?
    self.mac_wifi.upcase! if self.mac_wifi.present?
    self.manifest = Manifest.find_by(name: 'Common') if self.manifest.blank?
  end
  
  def computer_name
    no_s = self.number.present? ? "-#{number}" : nil
    test = self.manifest.name.include?('Test') ? 'T' : nil
    manifest = self.manifest.name.gsub('Test', '')
    room = self.room.present? ? self.room.gsub('R', '') : self.hardware_serial[-6..-1]
    "#{manifest}#{room}#{no_s}#{test}"
  end
  
  def munki_client_identifier
    manifest.name
  end

  def w
    resolution_x
  end

  def h
    resolution_y
  end
end

app/controllers/devices_controller.rb
class DevicesController < InheritedResources::Base
  before_action :authenticate_admin!, except: [:get_settings, :get_resolution, :create]

  def update
    update! { collection_path }
  end

  def get_settings
    @device = Device.find_by hardware_serial: params[:hardware_serial]
    
    if @device.present?
      @device.update_attribute :last_checkin, Time.now
    end

    render json: @device.as_json(only: [], methods: [:computer_name, :munki_client_identifier, :ip])
  end

  def get_resolution
    @device = Device.find_by hardware_serial: params[:hardware_serial]
    
    if @device.present?
      @device.update_attribute :last_checkin, Time.now
    end

    render json: @device.as_json(only: [], methods: [:w, :h])
  end
  
  protected
    def collection
      @devices ||= end_of_association_chain.ordered
    end
  
    def permitted_params
      params.permit!
    end

    def set_active_item
      @active = :devices
    end
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/views/devices/_form.html.haml
= simple_form_for(@device) do |f|
  = f.error_notification

  .form-inputs
    = f.input :hardware_serial #, input_html: { pattern: '.{12,}' }
    = f.input :room #, input_html: { pattern: '^R([0-9]{3})$' }
    = f.input :number
    = f.input :resolution_x #, input_html: { min: '16', max: '8192' }
    = f.input :resolution_y #, input_html: { min: '16', max: '8192' }
    = f.input :mac_en #, input_html: { pattern: '^([0-9A-F]{2}[:-]){5}([0-9A-F]{2})$' }
    = f.input :mac_wifi #, input_html: { pattern: '^([0-9A-F]{2}[:-]){5}([0-9A-F]{2})$' }
    = f.input :ip #, input_html: { pattern: '^10\.\d{1,3}\.\d{1,3}\.\d{1,3}$' }
    = f.association :manifest #, include_blank: false
    = f.input :model #, collection: %w(iMac MacMini), include_blank: false

  .form-actions
    = f.button :submit, class: 'btn btn-primary'

app/views/devices/edit.html.haml
.page-header
	%h1 Editing device

= render 'form'

= link_to 'Show', @device
\|
= link_to 'Back', devices_path

app/views/devices/index.html.haml
%p= new_button new_device_path, title: 'New Device', class: 'btn btn-default'

%table.table.table-striped
  %thead
    %tr
      %th Name
      %th.hidden-sm Model
      %th Room
      %th #
      %th S/N
      %th.hidden-sm Resolution
      %th IP
      %th Check-In
      %th Actions

  %tbody
    - @devices.each do |device|
      %tr{ :'data-id' => "#{device.id}" }
        %td= link_to device.computer_name, device
        %td.hidden-sm= device.model
        %td= device.room
        %td= device.number
        %td= device.hardware_serial
        %td.hidden-sm
          - if device.resolution_x.present?
            #{device.resolution_x}x#{device.resolution_y}
          - else
            \-
        %td= device.ip
        -# %td= device.last_checkin.strftime('%d/%m/%Y %I:%M') rescue '-'
        %td
          - if device.last_checkin.present?
            :javascript
              document.write(moment("#{device.last_checkin.strftime('%Y-%m-%d %H:%M')}").fromNow());
              $(function() {
                if(moment("#{device.last_checkin.strftime('%Y-%m-%d %H:%M')}").isBefore(moment().subtract('days', 5))) $('[data-id=#{device.id}] td').css('background-color', '#f2dede');
                if(moment("#{device.last_checkin.strftime('%Y-%m-%d %H:%M')}").isAfter(moment().subtract('days', 5))) $('[data-id=#{device.id}] td').css('background-color', '#dff0d8');
              });
          - else
            \-
        %td
          .btn-group
            = table_edit_button edit_device_path(device)
            = table_delete_button device

app/views/devices/new.html.haml
.page-header
	%h1 New device

= render 'form'

= link_to 'Back', devices_path

app/views/devices/show.html.haml
%p#notice= notice

%p
  %b Hardware serial:
  = @device.hardware_serial
%p
  %b Room:
  = @device.room
%p
  %b Number:
  = @device.number
%p
  %b Resolution x:
  = @device.resolution_x
%p
  %b Resolution y:
  = @device.resolution_y
%p
  %b Mac en:
  = @device.mac_en
%p
  %b Mac wifi:
  = @device.mac_wifi

%p
  %b Ip:
  = @device.ip
%p
  %b Manifest:
  = @device.manifest.name rescue '-'
%p
  %b Model:
  = @device.model

%p
  %b Last Check-In:
  = l @device.last_checkin rescue '-'

= link_to 'Edit', edit_device_path(@device)
\|
= link_to 'Back', devices_path