config/routes.rb
MacManager::Application.routes.draw do
  # devise_for :admins
  devise_for :admins, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}

  resources :manifests
  resources :devices
  # resources :devices do
    # match 'get_settings', via: :all #  => 'devices#get_settings'
  # end

  

  # You can have the root of your site routed with "root"
 root 'devices#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase
  get 'devices/:hardware_serial/get_settings' => 'devices#get_settings'
  get 'devices/:hardware_serial/get_resolution' => 'devices#get_resolution'
  
  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/manifest.rb
# == Schema Information
#
# Table name: manifests
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Manifest < ActiveRecord::Base
  has_many :devices

  # validates :name, presence: true
end

app/controllers/manifests_controller.rb
class ManifestsController < InheritedResources::Base
	before_action :authenticate_admin!

  protected
    def permitted_params
      params.permit!
    end

    def set_active_item
      @active = :manifests
    end
end

app/helpers/manifests_helper.rb
module ManifestsHelper
end

app/views/manifests/_form.html.haml
= simple_form_for(@manifest) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name

  .form-actions
    = f.button :submit, class: 'btn btn-primary'

app/views/manifests/edit.html.haml
.page-header
	%h1 Editing manifest

= render 'form'

= link_to 'Show', @manifest
\|
= link_to 'Back', manifests_path

app/views/manifests/index.html.haml
.page-header
  %h1 Listing manifests

%table.table.table-striped
  %thead
    %tr
      %th Name
      %th Actions

  %tbody
    - @manifests.each do |manifest|
      %tr
        %td= manifest.name
        %td
          = link_to 'Show', manifest, class: 'btn btn-default btn-xs' 
          = link_to 'Edit', edit_manifest_path(manifest), class: 'btn btn-primary btn-xs'
          = link_to 'Destroy', manifest, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: 'btn btn-danger btn-xs'

%br

= link_to 'New Manifest', new_manifest_path, class: 'btn btn-default'

app/views/manifests/new.html.haml
.page-header
	%h1 New manifest

= render 'form'

= link_to 'Back', manifests_path

app/views/manifests/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @manifest.name

= link_to 'Edit', edit_manifest_path(@manifest)
\|
= link_to 'Back', manifests_path