config/routes.rb
MacManager::Application.routes.draw do
  # devise_for :admins
  devise_for :admins, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}

  resources :manifests
  resources :devices
  # resources :devices do
    # match 'get_settings', via: :all #  => 'devices#get_settings'
  # end

  

  # You can have the root of your site routed with "root"
 root 'devices#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase
  get 'devices/:hardware_serial/get_settings' => 'devices#get_settings'
  get 'devices/:hardware_serial/get_resolution' => 'devices#get_resolution'
  
  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/layouts/_messages.html.erb
<% [:notice, :error, :alert].each do |level| %>
  <% unless flash[level].blank? %>
    <div class="alert alert-<%= flash_class(level) %>">
      <a class="close" data-dismiss="alert">×</a>
      <%= content_tag :p, flash[level] %>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.haml
!!! HTML
%html(lang="de")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta{content: "width=device-width, initial-scale=1.0", name: "viewport"}/
    %title= content_for?(:title) ? yield(:title) : "#{'DEV ' if Rails.env.development? }MacManager"
    = stylesheet_link_tag "application", media: "all"
    = javascript_include_tag "application"
    = csrf_meta_tags

  %body
    .navbar.navbar-inverse.navbar-fixed-top
      .container
        .navbar-header
          %button.navbar-toggle{type: "button"}(data-target=".navbar-collapse" data-toggle="collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.navbar-brand{ href: root_url }= Rails.env.development? ? "DEV MacManager" : "MacManager"
        %ul.nav.navbar-nav.pull-right
          - if signed_in?
            %li.dropdown{ class: @active == :user && 'active' }
              %a.dropdown-toggle(data-toggle='dropdown' href='#')
                %i.icon-user
                = current_admin.email
                %span.caret
              %ul.dropdown-menu
                %li= link_to "<i class='icon-signout'></i> Abmelden!".html_safe, destroy_admin_session_path, method: :delete
          - if false
            %li.inverse= link_to "<i class='icon-signin'></i> Anmelden".html_safe, new_user_session_path
        .navbar-collapse.collapse
          %ul.nav.navbar-nav
            %li{ class: @active == :devices && 'active' }= link_to "Devices", devices_path
            %li{ class: @active == :manifests && 'active' }= link_to "Manifests", manifests_path

    .container#main
      .row
        .col-md-12
          = render 'layouts/messages'
          
          = yield